# Generated by Django 2.2.1 on 2019-05-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=models.SET('default'), related_name='club', to='Club.Category')),
                ('dept', models.ForeignKey(on_delete=models.SET('default'), related_name='club', to='Club.Dept')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owing_club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
