# Generated by Django 2.2.1 on 2019-05-21 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='Club.Category'),
        ),
        migrations.AlterField(
            model_name='club',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='Club.Dept'),
        ),
        migrations.AlterField(
            model_name='club',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owing_club', to=settings.AUTH_USER_MODEL),
        ),
    ]
