# Generated by Django 2.2 on 2019-06-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_auto_20190521_1735'),
        ('Club', '0002_auto_20190516_1038'),
    ]

    operations = [
    ]
