# Generated by Django 2.2.1 on 2019-06-14 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_auto_20190521_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='apply_message',
            field=models.CharField(default='welcome', max_length=2000),
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='Club.Category'),
        ),
        migrations.AlterField(
            model_name='club',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='Club.Dept'),
        ),
        migrations.AlterField(
            model_name='club',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owing_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
