# Generated by Django 2.2 on 2019-06-14 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_merge_20190614_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='Club.Category'),
        ),
        migrations.AlterField(
            model_name='club',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='Club.Dept'),
        ),
        migrations.AlterField(
            model_name='club',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owing_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
