# Generated by Django 2.2 on 2019-06-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_auto_20190614_2035'),
        ('Club', '0003_merge_20190614_0528'),
        ('Club', '0003_auto_20190614_2234'),
    ]

    operations = [
    ]
