# Generated by Django 2.2 on 2019-06-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0005_merge_20190614_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_category', to='Club.Category'),
        ),
        migrations.AlterField(
            model_name='club',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_dept', to='Club.Dept'),
        ),
    ]
