# Generated by Django 2.2 on 2019-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0006_auto_20190615_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='intro',
            field=models.TextField(default='동아리 소개글을 작성해 주세요.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='apply_message',
            field=models.CharField(default='지원서는 성의있게 작성해 주세요!', max_length=2000),
        ),
    ]
