# Generated by Django 2.2 on 2019-06-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0007_auto_20190615_2158'),
        ('Club', '0005_merge_20190615_1637'),
    ]

    operations = [
    ]
