# Generated by Django 2.2 on 2019-06-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sent', to='Club.Club'),
        ),
    ]
