# Generated by Django 2.2.1 on 2019-06-14 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Club', '0003_auto_20190614_2234'),
        ('Join', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='join',
            options={'ordering': ['-auth_level', 'user__name']},
        ),
        migrations.AlterUniqueTogether(
            name='join',
            unique_together={('user', 'club')},
        ),
    ]
