# Generated by Django 2.2 on 2019-06-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0002_auto_20190614_2234'),
        ('Join', '0002_auto_20190614_2035'),
    ]

    operations = [
    ]
