# Generated by Django 2.2 on 2019-06-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0003_merge_20190615_1637'),
        ('Join', '0003_merge_20190614_2248'),
    ]

    operations = [
    ]
