# Generated by Django 2.2 on 2019-06-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_auto_20190615_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='Club.Club'),
        ),
    ]
