# Generated by Django 2.2 on 2019-06-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_auto_20190615_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='Club.Club'),
        ),
    ]
