# Generated by Django 2.2 on 2019-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0005_auto_20190615_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
