# Generated by Django 2.2 on 2019-06-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0003_merge_20190614_2248'),
        ('Document', '0006_document_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_club', to='Club.Club'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_type', to='Document.DocumentType'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Document.Document')),
                ('join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Join.Join')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
