# Generated by Django 2.2 on 2019-06-12 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Club', '0002_auto_20190610_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_club', to='Club.Club')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_club', to='Club.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileUploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
