# Generated by Django 2.2 on 2019-06-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='club',
        ),
    ]
