# Generated by Django 2.2 on 2019-06-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0003_imagemodel_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='club',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='user',
        ),
    ]
