# Generated by Django 2.2 on 2019-06-12 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Club', '0002_auto_20190610_1613'),
        ('Image', '0004_auto_20190613_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_club', to='Club.Club'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileUploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
